esphome:
  name: etrv2wifi-scanner

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  logs:
    esp32_ble_tracker: WARN
    ble_client: WARN
    logger: NONE

external_components:
  - source: github://dmitry-cherkas/esphome-danfoss-eco@v1.1.4

sensor:
  - platform: danfoss_eco_scanner
    id: scanner