esphome:
  name: etrv2wifi-scanner

esp32:
  board: esp32dev
  # esp-idf is the recommended (and current ESPHome default) framework for BLE projects
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  logs:
    esp32_ble_tracker: WARN
    ble_client: WARN
    logger: NONE

external_components:
  - source: github://borstel4711/esphome-danfoss-eco

sensor:
  - platform: danfoss_eco_scanner
    id: scanner
